# import = [
#     "~/.config/alacritty/kanagawa_dragon.toml"
# ]
import = [
    "~/.config/alacritty/catppuccin_mocha.toml"
]

live_config_reload = true

[window]
decorations = "Full"
startup_mode = "Windowed"
decorations_theme_variant = "Dark"

[env]
TERM = "xterm-256color"

[font]
# normal = { family = "JetBrainsMono Nerd Font" }
normal = { family = "FiraCode Nerd Font" }
size = 18

[cursor]
style = { shape = "Block", blinking = "Always" }

[[hints.enabled]]
command = "open" # On macOS
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
