import = [
    "C:/Users/jcms1/AppData/Roaming/alacritty/catppuccin-mocha.toml"
]

# import = [
#     "C:/Users/jcms1/AppData/Roaming/alacritty/kanagawa-dragon.toml"
# ]

working_directory = "E:/Files/dev"
live_config_reload = true

[window]
dynamic_title = true
# opacity = 0.9
padding = { x = 4, y = 4 }

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono" }
size = 12

[cursor]
style = { shape = "Block", blinking = "Always" }
