import = [
    "~/AppData/Roaming/alacritty/kanagawa_dragon.toml"
]
live_config_reload = true

[window]
dynamic_padding = true
dynamic_title = true

[font]
normal = { family = "JetBrains Mono" }
size = 13

[cursor]
style = { shape = "Block", blinking = "Always" }
