import = [
    "C:/Users/jcms1/AppData/Roaming/alacritty/kanagawa_dragon.toml"
]

working_directory = "E:/Files/dev"
live_config_reload = true

[window]
dynamic_title = true
dynamic_padding = true

[font]
normal = { family = "FiraCode Nerd Font" }
size = 14

[cursor]
style = { shape = "Block", blinking = "Always" }

