# import = [
#     "~/AppData/Roaming/alacritty/kanagawa_dragon.toml"
# ]

import = [
    "~/.config/alacritty/kanagawa_dragon.toml"
]

live_config_reload = true

[window]
# MacOS config
padding = { x = 16, y = 32 }
decorations = "Transparent"

# WSL config
dynamic_title = true
dynamic_padding = true

[font]
normal = { family = "FiraCode Nerd Font" }
size = 16

[cursor]
style = { shape = "Block", blinking = "Always" }

