import = [
    "~/.config/alacritty/kanagawa_dragon.toml"
]

live_config_reload = true

[window]
dynamic_title = true
dynamic_padding = true

[font]
normal = { family = "FiraCode Nerd Font" }
size = 14

[cursor]
style = { shape = "Block", blinking = "Always" }

